matches_service/web/matches/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.NewMatchesList.as_view(), name='new_matches_list'),
    path('matches/', views.MatchesList.as_view(), name='matches_list'),
    path('matches/<int:pk>/', views.MatchDetails.as_view()),
    path('generator/', views.GenerateNewMatchesView.as_view(), name='add_new_matches'),
    path('invites/', views.InvitesList.as_view()),
    path('remove_matches/', views.remove_matches, name='remove_matches')
]

matches_service/web/web/urls.py
from django.contrib import admin
from django.urls import path, include

# from matches import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('matches.urls'))
    # path('matches/', views.MatchesList.as_view()),
    # path('matches/<int:pk>/', views.MatchDetails.as_view()),
    # path('generator/', views.GenerateRandomMatchesView.as_view()),
    # path('invites/', views.InvitesList.as_view())
]

matches_service/web/matches/models.py
from django.db import models
from django.contrib.gis.db.models import PointField
from django.contrib.postgres.fields import ArrayField

import architect


@architect.install('partition', type='range', subtype='integer', constraint='240', column='minute_start')
# tutorial -> https://media.readthedocs.org/pdf/architect/latest/architect.pdf
# 1st partition ~ 0:00-4:00
# 2nd partition ~ 4:00-8:00
# 3rd partition ~ 8:00-12:00
# 4th partition ~ 12:00-16:00
# 5th partition ~ 16:00-20:00
# 6th partition ~ 20:00-24:00
# constraint = 240 (minutes) = 4h
class Match(models.Model):
    DISCIPLINES = (
        (0, 'football'),
        (1, 'basketball')
    )
    location = PointField()
    author_id = models.IntegerField()
    # author_nick = models.CharField(null=True) # chyba warto było by dodać to pole
    date = models.DateField()
    minute_start = models.IntegerField(null=True)
    minute_end = models.IntegerField(null=True)
    discipline = models.IntegerField(choices=DISCIPLINES, default=0)
    players = ArrayField(models.IntegerField(), size=100)


class Invite(models.Model):
    inviter = models.IntegerField()
    invitee = models.IntegerField()
    match = models.ForeignKey(Match, on_delete=models.CASCADE)

matches_service/web/matches/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
import re

from django.contrib.gis import forms as gis_forms

class MyGeoForm(gis_forms.Form):
    point = gis_forms.PointField(widget=
        gis_forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500}))


class GenerateRandomMatchesForm(forms.Form):
    playground_latitude = forms.FloatField(min_value=-90.0, max_value=90.0)
    playground_longitude = forms.FloatField(min_value=-180.0, max_value=180.0)
    author_id = forms.IntegerField()
    playing_from_hour = forms.IntegerField(min_value=0, max_value=24, initial=1)
    playing_to_hour = forms.IntegerField(min_value=0, max_value=24, initial=2)
    one_match_length_in_minutes = forms.IntegerField(min_value=1, initial=20)
    playing_from_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    playing_to_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    players = forms.CharField(initial='1 2 3 4 5 6')
    discipline = forms.ChoiceField(
        choices=((0, 'football'), (1, 'basketball')),
        required=True
    )

    def clean(self):
        start_hour = self.cleaned_data['playing_from_hour']
        end_hour = self.cleaned_data['playing_to_hour']
        match_length = self.cleaned_data['one_match_length_in_minutes']
        if start_hour >= end_hour:
            msg = u"End hour should be greater than start hour!"
            self._errors["playing_to_hour"] = self.error_class([msg])
        elif match_length > (end_hour - start_hour)*60:
            msg = u"Match length is too big to fit between start and end playing hours!"
            self._errors["one_match_length_in_minutes"] = self.error_class([msg])
        start_date = self.cleaned_data['playing_from_date']
        end_date = self.cleaned_data['playing_to_date']
        if start_date > end_date:
            msg = u"End date should be greater or equal to start date!"
            self._errors["playing_to_date"] = self.error_class([msg])
        players = self.cleaned_data['players']
        if players.replace(',', '').replace(' ', '').isdigit() == False:
            msg = u"You should put here only id numbers, seperated by spaces or commas!"
            self._errors["players"] = self.error_class([msg])

matches_service/web/matches/views.py
from django.http import HttpResponse
from django.http import Http404

from rest_framework.views import APIView

from django.contrib.gis.geos import Point
from rest_framework.response import Response
from rest_framework import status

from matches.models import Match, Invite
from matches.serializers import MatchesSerializer, InviteSerializer

import datetime

from .forms import GenerateRandomMatchesForm
from .tasks import create_match
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.contrib import messages
from django.shortcuts import redirect

import random

class MatchesList(APIView):
    def get(self, request, format=None):
        lat = request.GET.get('lat')
        lng = request.GET.get('lng')
        distance = request.GET.get('radius')
        author = request.GET.get('author')
        date = request.GET.get('date')
        players = request.GET.getlist('player')

        matches = Match.objects.all()

        if lat and lng and distance:
            point = Point(float(lng), float(lat))
            matches = matches.filter(location__distance_lt=(point, distance))
        elif lat or lng or distance:
            return HttpResponse(status=status.HTTP_400_BAD_REQUEST)

        if author:
            matches = matches.filter(author_id=int(author))

        if date:
            date = datetime.datetime.strptime(date, "%Y-%m-%d").date()
            matches = matches.filter(date=date)

        if players:
            matches = matches.filter(players__contains=players)

        serializer = MatchesSerializer(matches, many=True)

        return Response(serializer.data)

    def post(self, request, format=None):
        json = request.data
        serializer = MatchesSerializer(data=json)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def patch(self, request, format=None):
        id = request.data['id']
        new_player = request.data.get('new_player')
        remove_player = request.data.get('player_to_remove')

        match = Match.objects.get(id=id)
        if new_player:
            match.players.append(int(new_player))
        elif remove_player:
            match.players.remove(int(new_player))
        else:
            HttpResponse(status=status.HTTP_400_BAD_REQUEST)

        match.save()
        serializer = MatchesSerializer(match)

        return Response(serializer.data, status=status.HTTP_200_OK)


class MatchDetails(APIView):
    def get_object(self, pk):
        try:
            return Match.objects.get(pk=pk)
        except Match.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = MatchesSerializer(snippet)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = MatchesSerializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        snippet = self.get_object(pk)
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class InvitesList(APIView):
    def get(self, request):
        match = request.GET.get('match')
        inviter = request.GET.get('inviter')
        invitee = request.GET.get('invitee')

        invites = Invite.objects.all()

        if match:
            invites = invites.filter(match__id=int(match))
        if inviter:
            invites = invites.filter(inviter=int(inviter))
        if invitee:
            invites = invites.filter(invitee=int(invitee))

        serializer = InviteSerializer(invites, many=True)

        return Response(serializer.data)

    def post(self, request, format=None):
        json = request.data
        serializer = InviteSerializer(data=json)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class NewMatchesList(ListView):
    template_name = 'matches/new_matches_list.html'
    model = Match
    paginate_by = 10
    queryset = Match.objects.all().order_by('date', 'minute_start', 'minute_end', '-location')


class GenerateNewMatchesView(FormView):
    template_name = 'matches/add_new_matches.html'
    form_class = GenerateRandomMatchesForm

    def form_valid(self, form):
        playground_latitude = form.cleaned_data['playground_latitude']
        playground_longitude = form.cleaned_data['playground_longitude']
        author_id = form.cleaned_data['author_id']
        start_hour = form.cleaned_data['playing_from_hour']
        end_hour = form.cleaned_data['playing_to_hour']
        start_date_str = form.cleaned_data['playing_from_date']
        end_date_str = form.cleaned_data['playing_to_date']
        match_length = form.cleaned_data['one_match_length_in_minutes']
        players = set(form.cleaned_data['players'].replace(',', ' ').split())
        discipline = form.cleaned_data['discipline']
        start_date = start_date_str
        end_date = end_date_str

        all_matches = []
        for day_num in range(int((end_date - start_date).days) + 1):
            for time in range(int((end_hour - start_hour)*60/match_length)):
                match_date = start_date + datetime.timedelta(day_num)
                match_start = start_hour*60 + time*match_length
                match_end = match_start + match_length
                if len(players) > 12:
                    squad_size = 12
                else:
                    squad_size = len(players) - len(players)%2
                match_squad = random.sample(players, squad_size)
                all_matches.append({
                    "point": (playground_latitude, playground_longitude),
                    "author_id": author_id,
                    "date": datetime.datetime.combine(match_date, datetime.datetime.min.time()),
                    "minute_start": match_start,
                    "minute_end": match_end,
                    "squad": match_squad,
                    "discipline": discipline
                })
        for match in all_matches:
            create_match.delay(match)

        messages.success(self.request, 'Our workers are adding your new matches to our database using RabbitMQ! Please wait a moment and refresh this page. :-D ')

        return redirect('new_matches_list')


def remove_matches(request):
    Match.objects.all().delete()
    return redirect('new_matches_list')

matches_service/web/matches/templates/matches/add_new_matches.html
{% extends 'base.html' %}

{% block content %}
<h2>Add New Matches</h2>
<form method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock %}

matches_service/web/matches/templates/matches/generate_new_matches.html
{% extends 'base.html' %}

{% block content %}
<h2>Generate New Matches</h2>
<form method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock %}

matches_service/web/matches/templates/matches/generate_random_matches.html
{% extends 'base.html' %}

{% block content %}
<h2>Generate Random Matches</h2>
<form method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock %}

matches_service/web/matches/templates/matches/new_matches_list.html
{% extends 'base.html' %}

{% load mathfilters %}

{% block content %}
    <h2>Matches List</h2>

    <table>
        {% if object_list %}
            <tr>
                <td>Author_id</td>
                <td>Date</td>
                <td>Starting time</td>
                <td>Ending time</td>
                <td>Discipline</td>
                <td>Location coordinates</td>
                <td>Player ids</td>
            </tr>
        {% endif %}
        {% for match in object_list %}
            <tr>
                <td>{{ match.author_id }}</td>
                <td>{{ match.date }}</td>
                <td>{% if match.minute_start|intdiv:60 < 10 %}0{% endif %}{{ match.minute_start|intdiv:60}} :
                    {% if match.minute_start|mod:60 < 10 %}0{% endif %}{{ match.minute_start|mod:60}}
                </td>
                <td>{% if match.minute_end|intdiv:60 < 10 %}0{% endif %}{{ match.minute_end|intdiv:60}} :
                    {% if match.minute_end|mod:60 < 10 %}0{% endif %}{{ match.minute_end|mod:60}}
                </td>
                <td>{{ match.get_discipline_display }}</td>
                <td>({{ match.location.x }} , {{ match.location.y }})</td>
                <td>[
                    {% for player_id in match.players %}
                        {% if forloop.first %}
                            {{ player_id }}
                        {% else %}
                            , {{ player_id }}
                        {% endif %}
                    {% endfor %}]
                </td>
            </tr>
        {% endfor %}
    </table>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="/page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

{% endblock %}